spring.application.name=MeteoAIBot
spring.ai.openai.api-key=${OPENAI_API_KEY}
server.port=8081

# ======= PARAMETRES BASE DE DONNEES =======
# On utilise une base de donnees EN MEMOIRE pour etre sur que ca marche sans probleme de fichier
spring.datasource.url=jdbc:h2:mem:chatmemory;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=cherif
spring.datasource.password=12345

# ======= PARAMETRES H2 CONSOLE =======
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

# ======= PARAMETRES SPRING AI MEMORY =======
spring.ai.chat.memory.repository.jdbc.initialize-schema=always
spring.ai.chat.memory.repository.jdbc.schema=classpath:/schema/schema-h2db.sql